# Generated by Django 5.2.4 on 2025-08-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simcard",
            name="id_lote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simcards",
                to="core.lote",
            ),
        ),
        migrations.AlterField(
            model_name="simcard",
            name="id_operadora",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simcards",
                to="core.operadora",
            ),
        ),
    ]
