# Generated by Django 5.2.4 on 2025-08-22 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_simcard_id_lote_alter_simcard_id_operadora"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_venta", models.DateTimeField(auto_now_add=True)),
                (
                    "monto_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas",
                        to="core.cliente",
                    ),
                ),
                (
                    "id_simcard",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas",
                        to="core.simcard",
                    ),
                ),
                (
                    "id_usuario_propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
            },
        ),
    ]
