# Generated by Django 5.2.4 on 2025-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_venta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simcard",
            name="estado",
            field=models.CharField(
                choices=[
                    ("activa", "Activa"),
                    ("inactiva", "Inactiva"),
                    ("pendiente", "Pendiente de activación"),
                    ("perdida", "Perdida"),
                    ("robada", "Robada"),
                    ("desactivada", "Desactivada"),
                    ("vendida", "Vendida"),
                ],
                default="inactiva",
                max_length=20,
            ),
        ),
    ]
