# Generated by Django 5.2.4 on 2025-08-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_simcard_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
