# Generated by Django 5.2.4 on 2025-08-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_cliente_direccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="monto_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
