# Generated by Django 5.2.4 on 2025-09-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_venta_monto_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operadora",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="operadora",
            name="pais",
        ),
    ]
